import type { CapabilityBand, WorldApproach, WorldAttribute, WorldCharacter, WorldCharacterId, WorldMatchup, WorldMatchupId } from './types.ts';

const b = (floor: number, typical: number, ceiling: number): CapabilityBand => ({ floor, typical, ceiling });
const a = (v: Record<WorldAttribute, [number, number, number]>) => Object.fromEntries(Object.entries(v).map(([k, x]) => [k, b(...x)])) as Record<WorldAttribute, CapabilityBand>;

export const WORLD_CHARACTERS: Record<WorldCharacterId, WorldCharacter> = {
  yuji: { id:'yuji', name:'Yuji Itadori', shortName:'Yuji', version:'Shinjuku finale · original body', loadout:'Soul-aware strikes, Shrine, limited Blood Manipulation, RCT and Simple Domain. His unnamed domain is withheld because its complete rules are not established.', attributes:a({movement:[4,4,5],reaction:[4,4,5],martial:[4,5,5],technique:[2,3,4],tactical:[3,4,4],barrier:[1,2,3],output:[3,4,5],reinforcement:[4,5,5],rct:[2,3,4]}), abilities:['reinforced-melee','soul-strike','black-flash','shrine','rct','simple-domain'], traits:['soul-awareness','exceptional-physicality'], domain:null },
  mahito: { id:'mahito', name:'Mahito', shortName:'Mahito', version:'Shibuya · Instant Spirit Body available', loadout:'Idle Transfiguration, transfigured humans, body reshaping, Instant Spirit Body and Self-Embodiment of Perfection.', attributes:a({movement:[3,4,4],reaction:[3,4,4],martial:[2,3,4],technique:[4,5,5],tactical:[3,4,5],barrier:[4,5,5],output:[3,4,5],reinforcement:[3,4,5],rct:[0,0,0]}), abilities:['idle-transfiguration','body-reshape','transfigured-screen','domain-expansion'], traits:['soul-body','cursed-spirit'], domain:{id:'self-embodiment',name:'Self-Embodiment of Perfection',mastery:5,barrier:5,effectClass:'soul',sureHit:'Idle Transfiguration establishes touch-free soul contact.',targetFilter:'all-inside',confidence:'canon'} },
  yuta: { id:'yuta', name:'Yuta Okkotsu', shortName:'Yuta', version:'Shinjuku · original body before transfer', loadout:'Fully manifested Rika, demonstrated Copy stock, swordplay, RCT including output and Authentic Mutual Love.', attributes:a({movement:[3,4,5],reaction:[3,4,5],martial:[3,4,5],technique:[4,5,5],tactical:[3,4,5],barrier:[3,4,5],output:[4,5,5],reinforcement:[4,5,5],rct:[4,5,5]}), abilities:['swordplay','rika','thin-ice-breaker','rct','rct-output','domain-expansion'], traits:['vast-ce','positive-energy-output','rika-independent-actor'], domain:{id:'authentic-mutual-love',name:'Authentic Mutual Love',mastery:4,barrier:4,effectClass:'technique',sureHit:'One declared copied technique is assigned to the barrier.',targetFilter:'ce-recognized',confidence:'canon'} },
  jogo: { id:'jogo', name:'Jogo', shortName:'Jogo', version:'Shibuya · healthy', loadout:'Disaster Flames, Ember Insects, Maximum: Meteor and Coffin of the Iron Mountain.', attributes:a({movement:[4,5,5],reaction:[4,5,5],martial:[2,3,4],technique:[4,5,5],tactical:[3,4,4],barrier:[3,4,5],output:[4,5,5],reinforcement:[2,3,4],rct:[0,0,0]}), abilities:['disaster-flames','ember-insects','maximum-meteor','domain-expansion'], traits:['cursed-spirit','extreme-range'], domain:{id:'coffin',name:'Coffin of the Iron Mountain',mastery:4,barrier:4,effectClass:'environmental',sureHit:'Volcanic attacks and lethal heat overwhelm recognized targets.',targetFilter:'ce-recognized',confidence:'canon'} },
  maki: { id:'maki', name:'Maki Zenin', shortName:'Maki', version:'Sakurajima · fully realized Heavenly Restriction', loadout:'Zero cursed energy, sharpened senses and the Split Soul Katana. No other armory tools are assumed.', attributes:a({movement:[4,5,5],reaction:[4,5,5],martial:[4,5,5],technique:[0,0,0],tactical:[3,4,5],barrier:[0,0,0],output:[0,0,0],reinforcement:[5,5,5],rct:[0,0,0]}), abilities:['physical-melee','split-soul-katana','air-sense'], traits:['zero-ce','barrier-exception','soul-perception'], domain:null },
  hanami: { id:'hanami', name:'Hanami', shortName:'Hanami', version:'Kyoto Goodwill Event · healthy', loadout:'Disaster Plants, roots, Cursed Buds and Flower Field. The unrevealed domain is unavailable rather than invented.', attributes:a({movement:[2,3,4],reaction:[3,4,4],martial:[3,4,4],technique:[4,5,5],tactical:[3,4,4],barrier:[1,2,3],output:[3,4,5],reinforcement:[4,5,5],rct:[0,0,0]}), abilities:['disaster-plants','root-field','cursed-buds','flower-field'], traits:['cursed-spirit','extreme-durability','battlefield-control'], domain:null },
};

export const WORLD_MATCHUPS: readonly WorldMatchup[] = [
  {id:'yuji-mahito',fighterId:'yuji',opponentId:'mahito',mechanic:'Soul rules',promise:'Can Yuji create enough soul-damaging contact before Mahito establishes his domain?',lockedConditions:['Neutral enclosed arena','Technique knowledge','No outside help','Lethal intent']},
  {id:'yuta-jogo',fighterId:'yuta',opponentId:'jogo',mechanic:'Domain clash',promise:'Can Yuta and Rika convert contact before Jogo’s range and domain take control?',lockedConditions:['Neutral open arena','Basic reputation knowledge','Rika begins unmanifested','Lethal intent']},
  {id:'maki-hanami',fighterId:'maki',opponentId:'hanami',mechanic:'Zero CE targeting',promise:'Can Hanami’s physical control stop Maki before the soul-cutting blade reaches contact?',lockedConditions:['Wooded neutral arena','No preparation','Split Soul Katana equipped','Lethal intent']},
];
export const WORLD_APPROACHES: Record<WorldApproach,{label:string;description:string}> = {
  adaptive:{label:'Read & adapt',description:'Preserve major resources, learn the first interaction and answer the state that develops.'},
  pressure:{label:'Take initiative',description:'Contest setup immediately and accept a thinner defensive margin to reach the win condition first.'},
  counterplay:{label:'Draw the commitment',description:'Protect the first exchange, invite the major resource and punish its recovery window.'},
};
export function worldCharacter(id:WorldCharacterId){return WORLD_CHARACTERS[id]}
export function worldMatchup(id:WorldMatchupId){const m=WORLD_MATCHUPS.find(x=>x.id===id);if(!m)throw new Error(`Unknown matchup: ${id}`);return m}
