import { makeRng, type Rng } from '../rng.ts';
import { WORLD_APPROACHES, worldCharacter, worldMatchup } from './data.ts';
import type { CeBand, CombatantState, ConsequenceTier, EventPhase, FinalCombatantState, OutcomeDistribution, StoryBeat, WorldApproach, WorldAttribute, WorldCharacterId, WorldEvent, WorldMatchupId, WorldSimulationResult } from './types.ts';

type Check = { succeeded:boolean; margin:number; seeded:boolean };
type Ctx = { matchupId:WorldMatchupId; approach:WorldApproach; seed:string; rng:Rng; beat:number; events:WorldEvent[]; states:Partial<Record<WorldCharacterId,CombatantState>>; form:{label:string;fighter:number;opponent:number} };
const CONDITION=['Clear','Minor','Material','Severe','Critical','Terminal'] as const;
const CE=['Exhausted','Low','Strained','High','Full'] as const;
const FORMS=[{label:'Fighter reads the first beat',fighter:1,opponent:0},{label:'Both settle into normal rhythm',fighter:0,opponent:0},{label:'Opponent owns the first beat',fighter:0,opponent:1}] as const;

function fresh(id:WorldCharacterId):CombatantState{const c=worldCharacter(id);return{id,condition:0,ce:c.traits.includes('zero-ce')?0:4,technique:'ready',domainAvailable:!!c.domain,simpleDomain:c.abilities.includes('simple-domain')?'ready':'unavailable',soulDamage:0,effects:[],terminal:false}}
function makeCtx(matchupId:WorldMatchupId,approach:WorldApproach,seed:string):Ctx{const m=worldMatchup(matchupId);const rng=makeRng(`${matchupId}:${approach}:${seed}`);return{matchupId,approach,seed,rng,beat:0,events:[],states:{[m.fighterId]:fresh(m.fighterId),[m.opponentId]:fresh(m.opponentId)},form:FORMS[rng.int(FORMS.length)]!}}
function state(ctx:Ctx,id:WorldCharacterId){const s=ctx.states[id];if(!s)throw new Error(`${id} not active`);return s}
function attr(id:WorldCharacterId,key:WorldAttribute){return worldCharacter(id).attributes[key].typical}
function edge(approach:WorldApproach,kind:'attack'|'defense'|'domain'){if(approach==='pressure')return kind==='attack'?1:kind==='defense'?-1:0;if(approach==='counterplay')return kind==='defense'?1:kind==='attack'?-1:0;return kind==='domain'?1:0}
function check(ctx:Ctx,actor:number,defender:number):Check{const margin=actor-defender;if(margin>=4)return{succeeded:true,margin,seeded:false};if(margin<=-4)return{succeeded:false,margin,seeded:false};const p:{[k:string]:number}={'-3':.12,'-2':.22,'-1':.36,'0':.5,'1':.64,'2':.78,'3':.88};return{succeeded:ctx.rng.chance(p[String(margin)]??.5),margin,seeded:true}}
function emit(ctx:Ctx,e:Omit<WorldEvent,'id'|'beat'|'uncertainty'> & {check?:Check;uncertaintyLabel?:string}){if(state(ctx,e.actorId).terminal)throw new Error('Action after terminal');if(e.abilityId&&!worldCharacter(e.actorId).abilities.includes(e.abilityId))throw new Error(`${e.actorId} cannot use ${e.abilityId}`);ctx.beat++;const{check:roll,uncertaintyLabel,...rest}=e;const out:WorldEvent={...rest,id:`w1-e${String(ctx.beat).padStart(2,'0')}`,beat:ctx.beat,uncertainty:roll?.seeded?{label:uncertaintyLabel??'bounded timing/read check',margin:roll.margin,succeeded:roll.succeeded}:undefined};ctx.events.push(out);return out}
function injure(ctx:Ctx,id:WorldCharacterId,tier:ConsequenceTier,effect?:string){const s=state(ctx,id);s.condition=Math.max(s.condition,tier) as ConsequenceTier;if(effect&&!s.effects.includes(effect))s.effects.push(effect)}
function soul(ctx:Ctx,id:WorldCharacterId,tier:ConsequenceTier){const s=state(ctx,id);s.soulDamage=Math.max(s.soulDamage,tier) as ConsequenceTier}
function spend(ctx:Ctx,id:WorldCharacterId,n:number){const s=state(ctx,id);s.ce=Math.max(0,s.ce-n) as CeBand;if(s.ce===0&&!worldCharacter(id).traits.includes('zero-ce'))s.technique='exhausted'}
function burnout(ctx:Ctx,id:WorldCharacterId,phase:EventPhase,reason:string){const s=state(ctx,id);s.domainAvailable=false;s.technique='burned-out';if(!s.effects.includes('Technique burnout'))s.effects.push('Technique burnout');emit(ctx,{phase,actorId:id,targetIds:[],ruleId:'INT-DOM-BURNOUT',title:`${worldCharacter(id).shortName}'s domain ends`,summary:`${reason} The barrier falls and the imbued technique enters burnout.`,basis:'An established domain ending applies technique burnout unless a documented exception exists.',resolution:'state-consequence',confidence:'canon',changes:['Domain unavailable','Technique burned out']})}
function finish(ctx:Ctx,winnerId:WorldCharacterId,loserId:WorldCharacterId,e:Omit<WorldEvent,'id'|'beat'|'decisive'|'uncertainty'> & {check?:Check}){const l=state(ctx,loserId);l.condition=5;l.terminal=true;emit(ctx,{...e,decisive:true});return{winnerId,loserId}}

function yujiMahito(ctx:Ctx){
  const entry=check(ctx,attr('yuji','movement')+attr('yuji','martial')+ctx.form.fighter+edge(ctx.approach,'attack'),attr('mahito','technique')+attr('mahito','tactical')+ctx.form.opponent);
  if(entry.succeeded){injure(ctx,'mahito',1,'Body reshaping taxed');soul(ctx,'mahito',2);emit(ctx,{phase:'opening',actorId:'yuji',targetIds:['mahito'],abilityId:'soul-strike',ruleId:'INT-SOUL-ACCESS',title:'Yuji reaches the soul through the screen',summary:'Yuji reads the transfigured-body screen, forces close range and lands damage Mahito cannot erase by reshaping his body.',basis:'Yuji can perceive and damage the soul; reshaping body form does not freely erase soul damage.',resolution:'seeded-check',confidence:'canon',changes:['Mahito: minor body damage','Mahito: material soul damage'],check:entry})}
  else{injure(ctx,'yuji',2,'Cut by reshaped limbs');emit(ctx,{phase:'opening',actorId:'mahito',targetIds:['yuji'],abilityId:'transfigured-screen',ruleId:'INT-SUM-SCREEN',title:'Mahito crowds the first exchange',summary:'Transfigured bodies break Yuji’s line while a reshaped limb lands physical damage. Soul awareness prevents an effortless one-touch finish.',basis:'Independent bodies deny space. Yuji can guard his soul, but that is resistance rather than immunity.',resolution:'seeded-check',confidence:'canon',changes:['Yuji: material injury','Mahito retains range'],check:entry})}
  const activation=check(ctx,attr('mahito','barrier')+attr('mahito','reaction')+ctx.form.opponent-(entry.succeeded?2:0),attr('yuji','reaction')+attr('yuji','tactical')+ctx.form.fighter+edge(ctx.approach,'defense'));
  if(!activation.succeeded){emit(ctx,{phase:'escalation',actorId:'mahito',targetIds:['yuji'],abilityId:'domain-expansion',ruleId:'INT-DOM-ACTIVATION',title:'The domain activation is interrupted',summary:'Mahito starts Self-Embodiment, but Yuji reaches the activation beat before the barrier establishes.',basis:'A domain can be interrupted before establishment; no sure-hit exists until establishment completes.',resolution:'seeded-check',confidence:'canon',changes:['Domain not established','Yuji retains contact'],check:activation});soul(ctx,'mahito',5);return finish(ctx,'yuji','mahito',{phase:'finish',actorId:'yuji',targetIds:['mahito'],abilityId:entry.succeeded?'black-flash':'soul-strike',ruleId:entry.succeeded?'INT-BF-ELIGIBILITY':'INT-SOUL-CONSEQUENCE',title:entry.succeeded?'Black Flash converts the opening':'Soul-aware pressure converts the interruption',summary:entry.succeeded?'Legal cursed-energy contact creates the rhythm for Black Flash; the amplified soul-aware impact ends Mahito’s remaining form.':'Yuji stays attached through the failed expansion and chains soul-aware strikes until Mahito can no longer preserve his soul’s shape.',basis:'The finish follows an executable contact chain, not a random power critical.',resolution:'state-consequence',confidence:'inferred',changes:['Mahito: terminal soul damage','Fight ends']})}
  spend(ctx,'mahito',2);state(ctx,'mahito').technique='active';emit(ctx,{phase:'escalation',actorId:'mahito',targetIds:['yuji'],abilityId:'domain-expansion',ruleId:'INT-DOM-ESTABLISH',title:'Self-Embodiment establishes',summary:'Mahito completes the closed barrier and imposes touch-free soul contact. Yuji must answer the sure-hit.',basis:worldCharacter('mahito').domain!.sureHit,resolution:'seeded-check',confidence:'canon',changes:['Mahito: CE strained','Domain active'],check:activation});
  spend(ctx,'yuji',1);state(ctx,'yuji').simpleDomain='active';emit(ctx,{phase:'escalation',actorId:'yuji',targetIds:['mahito'],abilityId:'simple-domain',ruleId:'INT-DOM-SIMPLE',title:'Simple Domain buys a temporary pocket',summary:'Yuji interrupts the sure-hit inside a small boundary, but Mahito’s domain and ordinary attacks remain active.',basis:'Simple Domain temporarily interferes with a sure-hit; it does not destroy the domain or grant general immunity.',resolution:'hard-rule',confidence:'canon',changes:['Yuji: CE strained','Sure-hit temporarily suppressed']});
  const counter=check(ctx,attr('yuji','movement')+attr('yuji','martial')+ctx.form.fighter+edge(ctx.approach,'defense')-(state(ctx,'yuji').condition>=2?1:0),attr('mahito','reaction')+attr('mahito','technique')+ctx.form.opponent-(entry.succeeded?1:0));
  if(counter.succeeded){soul(ctx,'mahito',5);burnout(ctx,'mahito','finish','Yuji reaches the caster before barrier pressure peels away the defense.');return finish(ctx,'yuji','mahito',{phase:'finish',actorId:'yuji',targetIds:['mahito'],abilityId:'soul-strike',ruleId:'INT-DOM-CASTER-BREAK',title:'The counterattack breaks the caster',summary:'Yuji attacks from inside the shrinking Simple Domain, damages Mahito’s soul and collapses the barrier by defeating its caster.',basis:'Damaging the caster is a legal domain answer when the defender creates a real opportunity.',resolution:'seeded-check',confidence:'inferred',changes:['Mahito: terminal soul damage','Fight ends'],check:counter})}
  state(ctx,'yuji').simpleDomain='collapsed';emit(ctx,{phase:'finish',actorId:'mahito',targetIds:['yuji'],abilityId:'domain-expansion',ruleId:'INT-DOM-EROSION',title:'Barrier pressure erodes the defense',summary:'Yuji cannot reach Mahito before Simple Domain loses its shape, restoring the sure-hit.',basis:'Simple Domain can erode under sustained domain pressure.',resolution:'seeded-check',confidence:'canon',changes:['Simple Domain collapsed','Sure-hit restored'],check:counter});burnout(ctx,'mahito','finish','The restored sure-hit resolves the fight.');return finish(ctx,'mahito','yuji',{phase:'finish',actorId:'mahito',targetIds:['yuji'],abilityId:'idle-transfiguration',ruleId:'INT-SOUL-SURE-HIT',title:'Idle Transfiguration reaches the soul',summary:'Sustained sure-hit contact overwhelms Yuji’s active soul defense after his anti-domain pocket collapses.',basis:'Soul awareness is resistance, not indefinite immunity to an established soul sure-hit.',resolution:'hard-rule',confidence:'inferred',changes:['Yuji: terminal soul transfiguration','Fight ends']});
}

function clash(ctx:Ctx){const y=worldCharacter('yuta').domain!,j=worldCharacter('jogo').domain!;const margin=y.mastery+y.barrier+attr('yuta','output')+ctx.form.fighter+edge(ctx.approach,'domain')-(state(ctx,'yuta').condition>=2?2:0)-(j.mastery+j.barrier+attr('jogo','output')+ctx.form.opponent);if(margin>=4)return{result:'yuta' as const,margin,seeded:false};if(margin<=-4)return{result:'jogo' as const,margin,seeded:false};const roll=ctx.rng.next()+margin*.1;return{result:roll>.72?'yuta' as const:roll<.28?'jogo' as const:'contested' as const,margin,seeded:true}}
function yutaJogo(ctx:Ctx){
  spend(ctx,'yuta',1);state(ctx,'yuta').effects.push('Rika fully manifested');emit(ctx,{phase:'opening',actorId:'yuta',targetIds:['jogo'],abilityId:'rika',ruleId:'INT-SUM-INDEPENDENT',title:'Rika turns one approach into two',summary:'Yuta manifests Rika and splits the approach: Jogo must track the sword and an independent retreat-line attacker.',basis:'Rika acts independently rather than functioning as a passive stat bonus.',resolution:'hard-rule',confidence:'canon',changes:['Yuta: CE high','Rika active']});
  const range=check(ctx,attr('jogo','movement')+attr('jogo','technique')+ctx.form.opponent,attr('yuta','reaction')+attr('yuta','tactical')+1+ctx.form.fighter+edge(ctx.approach,'defense'));
  if(range.succeeded){injure(ctx,'yuta',2,'Burns through reinforcement');spend(ctx,'yuta',1);emit(ctx,{phase:'opening',actorId:'jogo',targetIds:['yuta'],abilityId:'disaster-flames',ruleId:'INT-RANGE-CONTROL',title:'Jogo keeps the lane volcanic',summary:'Overlapping flame catches Yuta’s route. RCT stabilizes the burn, but healing costs output and time.',basis:'RCT repairs survivable injury; it does not grant immunity or refund spent energy.',resolution:'seeded-check',confidence:'canon',changes:['Yuta: material burns','Yuta: CE strained'],check:range})}
  else{emit(ctx,{phase:'opening',actorId:'yuta',targetIds:['jogo'],abilityId:'rika',ruleId:'INT-SUM-PRESSURE',title:'The pincer removes Jogo’s clean reset',summary:'Yuta crosses the first flame line while Rika blocks the safest retreat, forcing close defense.',basis:'The opportunity comes from independent pressure lines, not a combined power score.',resolution:'seeded-check',confidence:'inferred',changes:['Yuta reaches close range','Jogo pressured'],check:range});const contact=check(ctx,attr('yuta','tactical')+attr('yuta','martial')+2+edge(ctx.approach,'attack'),attr('jogo','reaction')+attr('jogo','movement')+ctx.form.opponent);if(contact.succeeded){emit(ctx,{phase:'escalation',actorId:'yuta',targetIds:['jogo'],abilityId:'rika',ruleId:'INT-SUM-PIN',title:'Rika secures actual contact',summary:'Rika catches Jogo for one beat and gives Yuta the contact positive-energy output requires.',basis:'The anti-curse interaction is gated behind legal contact.',resolution:'seeded-check',confidence:'inferred',changes:['Jogo pinned','RCT-output contact legal'],check:contact});return finish(ctx,'yuta','jogo',{phase:'finish',actorId:'yuta',targetIds:['jogo'],abilityId:'rct-output',ruleId:'INT-RCT-CURSE',title:'Positive energy converts the contact',summary:'Yuta outputs positive energy directly into the cursed spirit and destroys its manifested structure.',basis:'Direct positive-energy output is exceptionally destructive to cursed spirits after contact.',resolution:'hard-rule',confidence:'inferred',changes:['Jogo: exorcised','Fight ends']})}}
  spend(ctx,'jogo',2);spend(ctx,'yuta',2);state(ctx,'jogo').technique='active';state(ctx,'yuta').technique='active';const d=clash(ctx);emit(ctx,{phase:'escalation',actorId:'yuta',targetIds:['jogo'],abilityId:'domain-expansion',ruleId:'INT-DOM-CLASH',title:'Authentic Mutual Love meets Coffin of the Iron Mountain',summary:d.result==='contested'?'The barriers overlap without immediate dominance. Sure-hits cancel in the contested space while direct actions remain legal.':d.result==='yuta'?'Yuta secures the overlap first and suppresses Jogo’s sure-hit without erasing ordinary flame.':'Jogo wins the current construction and output exchange, breaking Yuta’s barrier before its sure-hit stabilizes.',basis:'The clash compares mastery, construction, current output, timing and injury—not one permanent domain score.',resolution:d.seeded?'seeded-check':'state-consequence',confidence:'inferred',changes:[d.result==='contested'?'Sure-hits canceled in overlap':d.result==='yuta'?'Yuta controls overlap':'Yuta barrier breaks'],check:d.seeded?{succeeded:d.result==='yuta',margin:d.margin,seeded:true}:undefined,uncertaintyLabel:'bounded domain-clash check'});
  if(d.result==='jogo'){burnout(ctx,'yuta','finish','Coffin breaks Authentic Mutual Love.');burnout(ctx,'jogo','finish','The surviving sure-hit completes its effect.');return finish(ctx,'jogo','yuta',{phase:'finish',actorId:'jogo',targetIds:['yuta'],abilityId:'domain-expansion',ruleId:'INT-DOM-ENVIRONMENT',title:'The volcanic sure-hit outpaces recovery',summary:'Yuta enters burnout inside Jogo’s surviving domain. RCT cannot indefinitely out-heal continuous lethal heat.',basis:'Healing is rate- and resource-limited.',resolution:'hard-rule',confidence:'inferred',changes:['Yuta: terminal burns','Fight ends']})}
  if(d.result==='yuta'){emit(ctx,{phase:'finish',actorId:'yuta',targetIds:['jogo'],abilityId:'thin-ice-breaker',ruleId:'INT-COPY-DECLARED',title:'A declared copy opens the lane',summary:'With Jogo’s sure-hit suppressed, Yuta distorts the guard while Rika closes from the other side.',basis:'Only Copy stock declared for this version is available.',resolution:'hard-rule',confidence:'canon',changes:['Jogo guard displaced','Contact created']});burnout(ctx,'yuta','finish','The decisive contact is secured and the barrier releases.');state(ctx,'jogo').domainAvailable=false;return finish(ctx,'yuta','jogo',{phase:'finish',actorId:'yuta',targetIds:['jogo'],abilityId:'rct-output',ruleId:'INT-RCT-CURSE',title:'Yuta converts the domain edge',summary:'Rika holds the line for one beat and Yuta applies positive energy directly to Jogo.',basis:'Domain control creates the opportunity; contact supplies the win condition.',resolution:'hard-rule',confidence:'inferred',changes:['Jogo: exorcised','Fight ends']})}
  const inside=check(ctx,attr('yuta','tactical')+attr('yuta','martial')+2+edge(ctx.approach,'attack')-(state(ctx,'yuta').condition>=2?1:0),attr('jogo','reaction')+attr('jogo','movement')+ctx.form.opponent);
  if(inside.succeeded){emit(ctx,{phase:'finish',actorId:'yuta',targetIds:['jogo'],abilityId:'rika',ruleId:'INT-DOM-CONTESTED-ACTION',title:'Rika decides the contested space',summary:'With sure-hits canceled, Rika remains a legal independent attacker and pins Jogo for Yuta.',basis:'A contested clash does not freeze fighters or summons.',resolution:'seeded-check',confidence:'inferred',changes:['Jogo pinned','Contact created'],check:inside});burnout(ctx,'jogo','finish','Jogo loses concentration under two-body pressure.');burnout(ctx,'yuta','finish','The opposing barrier falls and the overlap collapses.');return finish(ctx,'yuta','jogo',{phase:'finish',actorId:'yuta',targetIds:['jogo'],abilityId:'rct-output',ruleId:'INT-RCT-CURSE',title:'Contact becomes exorcism',summary:'Yuta converts Rika’s pin with direct positive-energy output before Jogo can rebuild range.',basis:'The finish requires the independently resolved pin and contact.',resolution:'hard-rule',confidence:'inferred',changes:['Jogo: exorcised','Fight ends']})}
  burnout(ctx,'yuta','finish','Direct flame destabilizes Yuta’s barrier.');burnout(ctx,'jogo','finish','The clash ends as Authentic Mutual Love collapses.');return finish(ctx,'jogo','yuta',{phase:'finish',actorId:'jogo',targetIds:['yuta'],abilityId:'disaster-flames',ruleId:'INT-DOM-CONTESTED-ACTION',title:'Direct flame wins the overlap',summary:'Sure-hits cancel, but ordinary flame remains legal. Jogo keeps Rika off-line and finishes the injured sorcerer.',basis:'Sure-hit cancellation does not cancel ordinary techniques.',resolution:'seeded-check',confidence:'inferred',changes:['Yuta: terminal burns','Fight ends'],check:inside});
}

function makiHanami(ctx:Ctx){
  const buds=check(ctx,attr('hanami','technique')+attr('hanami','tactical')+ctx.form.opponent,attr('maki','reaction')+attr('maki','movement')+ctx.form.fighter+edge(ctx.approach,'defense'));if(buds.succeeded)injure(ctx,'maki',1,'Cursed Bud impact wound');emit(ctx,{phase:'opening',actorId:'hanami',targetIds:['maki'],abilityId:'cursed-buds',ruleId:'INT-HR-ZERO-CE',title:'Cursed Buds find no cursed energy',summary:buds.succeeded?'A bud clips Maki as a projectile, but its cursed-energy drain has no resource to consume.':'Maki reads the projectile through the air. Even contact would find no cursed energy to drain.',basis:'Zero CE blocks the drain condition, not physical impact.',resolution:'seeded-check',confidence:'canon',changes:buds.succeeded?['Maki: minor physical wound','CE drain: no effect']:['CE drain: no valid target'],check:buds});
  const entry=check(ctx,attr('maki','movement')+attr('maki','martial')+ctx.form.fighter+edge(ctx.approach,'attack')-(state(ctx,'maki').condition?1:0),attr('hanami','technique')+attr('hanami','tactical')+ctx.form.opponent+1);
  if(entry.succeeded){soul(ctx,'hanami',3);injure(ctx,'hanami',3,'Split Soul Katana wound');emit(ctx,{phase:'escalation',actorId:'maki',targetIds:['hanami'],abilityId:'split-soul-katana',ruleId:'INT-TOOL-SOUL-CUT',title:'The blade bypasses the durability contest',summary:'Maki crosses the root pattern and lands the Split Soul Katana. Hanami’s toughness cannot substitute for soul defense.',basis:'The tool cuts the soul when wielded by someone able to perceive it; contact was resolved separately.',resolution:'seeded-check',confidence:'canon',changes:['Hanami: severe body wound','Hanami: severe soul wound'],check:entry});const counter=check(ctx,attr('hanami','technique')+attr('hanami','output')+ctx.form.opponent-2,attr('maki','reaction')+attr('maki','martial')+ctx.form.fighter);if(!counter.succeeded){soul(ctx,'hanami',5);return finish(ctx,'maki','hanami',{phase:'finish',actorId:'maki',targetIds:['hanami'],abilityId:'split-soul-katana',ruleId:'INT-TOOL-SOUL-CUT',title:'Hanami cannot rebuild the line',summary:'The first soul wound slows the counter-pattern. Maki stays inside the roots and lands the second cut.',basis:'The finish follows a successful entry and persistent soul damage.',resolution:'seeded-check',confidence:'inferred',changes:['Hanami: exorcised','Fight ends'],check:counter})}injure(ctx,'maki',3,'Root burst at close range');emit(ctx,{phase:'finish',actorId:'hanami',targetIds:['maki'],abilityId:'root-field',ruleId:'INT-RANGE-PHYSICAL',title:'Hanami detonates the ground',summary:'Hanami accepts the soul wound and erupts physical roots at point-blank range, breaking Maki’s follow-up.',basis:'Zero CE does not make Maki intangible to manually aimed matter.',resolution:'seeded-check',confidence:'inferred',changes:['Maki: severe injury','Distance reopened'],check:counter});}
  else{injure(ctx,'maki',3,'Pinned by layered roots');emit(ctx,{phase:'escalation',actorId:'hanami',targetIds:['maki'],abilityId:'root-field',ruleId:'INT-RANGE-PHYSICAL',title:'The root field closes before sword range',summary:'Hanami layers physical roots through Maki’s route. The attack uses matter, not cursed-energy recognition.',basis:'Heavenly Restriction grants targeting exceptions, not physical intangibility.',resolution:'seeded-check',confidence:'canon',changes:['Maki: severe injury','Maki held outside sword range'],check:entry});}
  const escape=check(ctx,attr('maki','reinforcement')+attr('maki','martial')-2+edge(ctx.approach,'defense'),attr('hanami','output')+attr('hanami','technique')+ctx.form.opponent-(state(ctx,'hanami').condition>=3?2:0));if(escape.succeeded){emit(ctx,{phase:'finish',actorId:'maki',targetIds:['hanami'],abilityId:'physical-melee',ruleId:'INT-HR-PHYSICAL',title:'Maki breaks the hold',summary:'Raw physical force tears open the root cage and the recoil line leads directly back to Hanami.',basis:'The escape uses demonstrated Heavenly Restriction physicality, not invented cursed energy.',resolution:'seeded-check',confidence:'canon',changes:['Root hold broken','Sword contact created'],check:escape});soul(ctx,'hanami',5);return finish(ctx,'maki','hanami',{phase:'finish',actorId:'maki',targetIds:['hanami'],abilityId:'split-soul-katana',ruleId:'INT-TOOL-SOUL-CUT',title:'The escape becomes the killing line',summary:'Hanami cannot reset after the cage breaks. The Split Soul Katana reaches the curse’s soul and completes the exorcism.',basis:'A legal physical escape creates contact; the soul rule resolves only afterward.',resolution:'hard-rule',confidence:'inferred',changes:['Hanami: exorcised','Maki remains severely injured','Fight ends']})}return finish(ctx,'hanami','maki',{phase:'finish',actorId:'hanami',targetIds:['maki'],abilityId:'disaster-plants',ruleId:'INT-RANGE-PHYSICAL',title:'The physical cage compounds the injury',summary:'Maki cannot break the layered roots before a second wave drives through the pinned position. No domain or CE-targeting shortcut is invented.',basis:'The finish is the physical consequence of the failed escape.',resolution:'seeded-check',confidence:'inferred',changes:['Maki: terminal physical injury','Fight ends'],check:escape});
}

function story(events:WorldEvent[]):StoryBeat[]{const labels={opening:'Opening',escalation:'Turning point',finish:'Finish'} as const;return(['opening','escalation','finish'] as const).map(phase=>{const e=events.filter(x=>x.phase===phase);return{phase,label:labels[phase],text:e.map(x=>x.summary).join(' '),eventIds:e.map(x=>x.id)}}).filter(x=>x.eventIds.length)}
function final(s:CombatantState):FinalCombatantState{return{id:s.id,condition:s.condition,conditionLabel:CONDITION[s.condition],ce:s.ce,ceLabel:worldCharacter(s.id).traits.includes('zero-ce')?'None by constitution':CE[s.ce],technique:s.technique,domainAvailable:s.domainAvailable,soulDamage:s.soulDamage,effects:[...s.effects]}}
export function simulateWorldFight(input:{matchupId:WorldMatchupId;approach:WorldApproach;seed:string}):WorldSimulationResult{const seed=input.seed.trim().toUpperCase();if(!seed)throw new Error('Seed required');if(!(input.approach in WORLD_APPROACHES))throw new Error('Unknown approach');const ctx=makeCtx(input.matchupId,input.approach,seed);const terminal=input.matchupId==='yuji-mahito'?yujiMahito(ctx):input.matchupId==='yuta-jogo'?yutaJogo(ctx):makiHanami(ctx);const decisive=ctx.events.findLast(e=>e.decisive);if(!decisive)throw new Error('No decisive event');const m=worldMatchup(input.matchupId);return{ruleset:'world-1',matchupId:input.matchupId,approach:input.approach,seed,fightForm:ctx.form.label,winnerId:terminal.winnerId,loserId:terminal.loserId,verdict:`${worldCharacter(terminal.winnerId).shortName} wins through ${decisive.title.toLowerCase()}.`,decisiveRule:decisive.ruleId,events:ctx.events,story:story(ctx.events),finalStates:[final(state(ctx,m.fighterId)),final(state(ctx,m.opponentId))]}}
export function worldOutcomeDistribution(input:{matchupId:WorldMatchupId;approach:WorldApproach;seed:string;sampleSize?:number}):OutcomeDistribution{const m=worldMatchup(input.matchupId),n=input.sampleSize??48,counts=new Map<WorldCharacterId,number>([[m.fighterId,0],[m.opponentId,0]]);for(let i=0;i<n;i++){const r=simulateWorldFight({matchupId:input.matchupId,approach:input.approach,seed:`${input.seed}-${i}`});counts.set(r.winnerId,(counts.get(r.winnerId)??0)+1)}return{sampleSize:n,outcomes:[...counts].map(([winnerId,count])=>({winnerId,count}))}}
